// Short sessions and honest, distinct-word activity, separate from recall ratings.
export const dayKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export function createJourney(cards,saved={},clock=()=>new Date()){
 const valid=new Set(cards.map(c=>c.id));let days={},round=null;
 const cleanRatings=(input,allowed=valid)=>Object.fromEntries(Object.entries(input&&typeof input==='object'?input:{}).filter(([id,status])=>allowed.has(Number(id))&&['known','weak'].includes(status)));
 for(const [day,ratings]of Object.entries(saved?.days||{})){if(/^\d{4}-\d{2}-\d{2}$/.test(day))days[day]=cleanRatings(ratings);}
 if(Array.isArray(saved?.round?.ids)){const ids=[...new Set(saved.round.ids.filter(id=>valid.has(id)))].slice(0,20);if(ids.length)round={ids,ratings:cleanRatings(saved.round.ratings,new Set(ids))};}
 const state=()=>{const today=dayKey(clock()),ratings=round?.ratings||{},done=Object.keys(ratings).length;return {today,totalToday:Object.keys(days[today]||{}).length,round:round?{...structuredClone(round),done,total:round.ids.length,complete:done===round.ids.length,known:Object.values(ratings).filter(x=>x==='known').length,weak:round.ids.filter(id=>ratings[id]==='weak')}:null};};
 return {state,start(ids,size=10){if(![5,10,20].includes(size))throw new Error('Invalid session size');const chosen=[...new Set(ids.filter(id=>valid.has(id)))].slice(0,size);if(!chosen.length)throw new Error('No words available');round={ids:chosen,ratings:{}};return state();},cancel(){round=null;},record(id,status){if(!valid.has(id)||!['known','weak'].includes(status))throw new Error('Invalid activity');const day=dayKey(clock());days[day]||={};days[day][id]=status;if(round&&round.ids.includes(id))round.ratings[id]=status;return state();},next(){return round?.ids.find(id=>!round.ratings[id])??null;},week(){return Array.from({length:7},(_,i)=>{const date=new Date(clock());date.setDate(date.getDate()-6+i);const key=dayKey(date);return {key,date,count:Object.keys(days[key]||{}).length};});},serialize(){const keys=Object.keys(days).sort().slice(-90);return {days:Object.fromEntries(keys.map(k=>[k,days[k]])),round:round?structuredClone(round):null};}};
}
