import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {createPractice,normalize,cleanProgress} from '../study.js';import {createJourney,dayKey} from '../journey.js';
const root=fileURLToPath(new URL('../',import.meta.url)),cards=JSON.parse(fs.readFileSync(root+'cards.json','utf8'));
const m=createPractice(cards);
for(const c of cards){for(const direction of ['en','ja']){m.choose(c.id);m.configure({direction});assert.equal(m.state().revealed,false);m.reveal();assert.equal(m.state().card.id,c.id);assert.equal(m.state().revealed,true);m.hide();}}
assert.throws(()=>m.choose(9999));assert.throws(()=>m.configure({scope:'bad'}));assert.throws(()=>m.rate('known'));m.configure({scope:'weak'});assert.equal(m.state().card,null);m.choose(1);assert.equal(m.state().scope,'all');m.reveal();m.rate('weak');m.configure({scope:'weak'});assert.deepEqual(m.state().deck,[1]);m.reveal();m.rate('known');assert.equal(m.state().card,null);assert.equal(m.state().counts.known,1);m.configure({scope:'all',category:'equipment',shuffle:true});assert.ok(m.state().deck.every(id=>cards[id-1].category==='equipment'));assert.equal(new Set(m.state().deck).size,m.state().deck.length);const id=m.state().card.id;m.toggleStar();m.configure({scope:'star'});assert.deepEqual(m.state().deck,[id]);const restored=createPractice(cards,m.serialize());assert.equal(restored.mark(id).star,true);assert.equal(restored.state().counts.known,1);assert.equal(normalize('kōkan'),'kokan');assert.equal(normalize('カーテン'),normalize('かーてん'));assert.deepEqual(cleanProgress({'99999':{status:'known'},'1':{status:'oops'}},cards),{});
class Element{constructor(id=''){this.id=id;this.hidden=false;this.value='';this.textContent='';this.children=[];this.dataset={};this.attributes={};this.style={setProperty(){}};this.classList={toggle(){}};}append(...args){this.children.push(...args);}replaceChildren(...args){this.children=[...args];}setAttribute(k,v){this.attributes[k]=v;}addEventListener(){}scrollIntoView(){}showModal(){this.open=true;}close(){this.open=false;}}
const html=fs.readFileSync(root+'index.html','utf8'),elements={},translations=[],registered={};
for(const x of html.matchAll(/id="([^"]+)"/g))elements[x[1]]=new Element(x[1]);for(const x of html.matchAll(/data-t="([^"]+)"/g)){const el=new Element();el.dataset.t=x[1];translations.push(el);}
const document={getElementById(id){assert.ok(elements[id],'Missing '+id);return elements[id];},createElement(){return new Element();},querySelectorAll(q){return q==='[data-t]'?translations:[];},documentElement:{style:{setProperty(){}}},body:new Element(),addEventListener(){},modelContext:{registerTool(t){registered[t.name]=t;}}};
const memory={};const context=vm.createContext({document,window:{addEventListener(){},matchMedia(){return {matches:false};},scrollTo(){},scrollY:0},localStorage:{getItem:k=>memory[k]||null,setItem(k,v){memory[k]=v;}},createPractice,createJourney,normalize,structuredClone,AbortController,fetch:async()=>({ok:true,json:async()=>cards}),console,Promise});
vm.runInContext(fs.readFileSync(root+'app.js','utf8').replace(/^import[^\n]+\n/gm,''),context);await new Promise(r=>setImmediate(r));
assert.equal(elements['question-word'].textContent,cards[0].english);elements.response.value='my answer';elements.reveal.onclick();assert.equal(elements['answer-word'].textContent,cards[0].japanese);assert.equal(elements.response.value,'my answer');elements['answer-image'].onload();assert.equal(elements['answer-image'].hidden,false);
elements['ja-mode'].onclick();assert.equal(elements['answer-content'].hidden,true);elements.reveal.onclick();elements['answer-image'].onload();assert.equal(elements['answer-image'].hidden,false);assert.equal(elements['answer-word'].textContent,cards[0].english);
elements['zoom-card'].onclick();assert.equal(elements['image-dialog'].open,true);elements['close-dialog'].onclick();assert.equal(elements['image-dialog'].open,false);elements['rate-weak'].onclick();assert.equal(elements['weak-count'].textContent,1);assert.equal(elements['answer-content'].hidden,true);assert.ok(JSON.parse(memory['care-words-v2']).progress['1'].status==='weak');elements['library-nav'].onclick();assert.equal(elements['library-view'].hidden,false);elements['word-search'].value='wheelchair';elements['word-search'].oninput();assert.ok(elements['word-grid'].children.length>0);elements['word-grid'].children[0].onclick();assert.equal(elements['study-view'].hidden,false);elements['ui-language'].onclick();assert.equal(document.documentElement.lang,'ja');assert.equal(elements['view-title'].textContent,'ことばの時間。');elements['card-number'].value='840';elements['go-card'].onclick();assert.equal(elements['question-word'].textContent,cards.at(-1).japanese);
registered.select_care_word_question.execute({cardNumber:131,direction:'en'});assert.equal(registered.get_care_word_question.execute().cardNumber,131);registered.reveal_care_word_answer.execute();assert.equal(registered.get_care_word_question.execute().answerVisible,true);assert.throws(()=>registered.select_care_word_question.execute({cardNumber:9999}));
// Session totals stay stable as filtered practice decks shrink; repeated ratings count once.
let now=new Date(2026,9,4,23,59);const journey=createJourney(cards,{},()=>now);
journey.start([1,2,3,4,5,6],5);assert.equal(journey.state().round.total,5);
journey.record(1,'weak');journey.record(1,'known');assert.equal(journey.state().totalToday,1);assert.equal(journey.state().round.done,1);
for(const id of [2,3,4,5])journey.record(id,id===3?'weak':'known');
assert.equal(journey.state().round.complete,true);assert.deepEqual(journey.state().round.weak,[3]);assert.equal(journey.next(),null);
const resumed=createJourney(cards,journey.serialize(),()=>now);assert.equal(resumed.state().round.done,5);assert.equal(resumed.state().totalToday,5);
now=new Date(2026,9,5,0,1);assert.equal(journey.state().totalToday,0);journey.record(1,'known');assert.equal(journey.week().at(-2).count,5);assert.equal(journey.state().totalToday,1);journey.cancel();assert.equal(journey.state().round,null);
assert.throws(()=>journey.start([],10));journey.start([1,1,2,99999],20);assert.equal(journey.state().round.total,2);assert.throws(()=>journey.record(99999,'known'));
// The actual app reaches a completion dialog and can retry just its weak words.
elements['session-size'].value='5';elements['start-session'].onclick();assert.equal(elements['session-active'].hidden,false);
for(let i=0;i<5;i++){elements.reveal.onclick();elements[i===0?'rate-weak':'rate-known'].onclick();}
assert.equal(elements['complete-dialog'].open,true);assert.equal(elements['complete-known'].textContent,4);assert.equal(elements['complete-weak'].textContent,1);assert.equal(elements['today-count'].textContent,6);
elements['review-set'].onclick();assert.equal(elements['complete-dialog'].open,false);elements.reveal.onclick();elements['speak-answer'].onclick();assert.ok(elements['speech-status'].textContent.includes('音声'));elements['rate-known'].onclick();assert.equal(elements['complete-dialog'].open,true);assert.equal(elements['complete-known'].textContent,1);assert.equal(elements['review-set'].hidden,true);assert.equal(elements['today-count'].textContent,6);elements['finish-session'].onclick();assert.equal(elements['complete-dialog'].open,false);assert.equal(elements['session-active'].hidden,true);
// Supported speech selects a matching language and cancels stale callbacks.
let spoken,stops=0;context.window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};context.window.speechSynthesis={getVoices:()=>[{lang:'ja-JP'},{lang:'en-US'}],cancel(){stops++;},speak(u){spoken=u;u.onstart();}};
elements.reveal.onclick();elements['slow-speech'].onclick();elements['speak-answer'].onclick();assert.equal(spoken.lang,'ja-JP');assert.equal(spoken.rate,.7);assert.equal(elements['speak-answer'].attributes['aria-pressed'],'true');const stale=spoken;elements['ja-mode'].onclick();stale.onstart();assert.equal(elements['speak-answer'].attributes['aria-pressed'],'false');elements.reveal.onclick();elements['speak-answer'].onclick();assert.equal(spoken.lang,'en-US');assert.ok(stops>0);
// Finishing an exhausted weak collection disables a next set instead of opening an empty one.
elements['scope-nav'].children.find(b=>b.dataset.scope==='weak').onclick();elements['session-size'].value='10';elements['start-session'].onclick();elements.reveal.onclick();elements['rate-known'].onclick();assert.equal(elements['complete-dialog'].open,true);assert.equal(elements['another-set'].disabled,true);elements['finish-session'].onclick();assert.equal(elements['study-empty'].hidden,false);
// Illustrated chapters and library previews map to the same source collection.
assert.equal(elements['chapter-nav'].children.length,5);assert.equal(elements['category-tracks'].children.length,5);
elements['chapter-nav'].children[3].onclick();assert.ok(elements['scene-image'].src.includes('/health.webp'));assert.equal(elements['study-view'].hidden,false);assert.ok(elements['category-badge'].textContent.includes('健康'));
elements['library-nav'].onclick();elements['word-search'].value='';elements['word-search'].oninput();assert.ok(elements['word-grid'].children.every(b=>b.children[0]?.src?.includes('/thumbs/')));assert.ok(elements['word-grid'].children.length>0);const firstTile=elements['word-grid'].children[0];firstTile.onclick();assert.equal(elements['answer-content'].hidden,true);assert.equal(elements['study-view'].hidden,false);
console.log('840 words ×2 directions, filters, randomization, rating/review, persistence, search, image, language UI and agent-tool checks passed.');
